import { StoreTypes } from "types";

export const mockCommands: Array<StoreTypes.ICommand> = [
  {
    id: 1,
    departmentId: 14,
    name: "Разработка СД",
    taskIds: [],
    userIds: [],
    managerUserId: 1,
    description: "Команда по разработка Сд элементов",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    departmentId: 14,
    name: "Разработка приложений по мониторингу датчиков",
    taskIds: [],
    userIds: [],
    managerUserId: 1,
    description: "Команда по разработка приложений по мониторингу датчиков",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    departmentId: 14,
    name: "Разработка модулей фильтрации",
    taskIds: [],
    userIds: [],
    managerUserId: 1,
    description: "Команда по разработка модулей фильтрации",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    departmentId: 14,
    name: "Разработка корпоративных приложений",
    taskIds: [],
    userIds: [],
    managerUserId: 1,
    description: "Команда по разработка корпоративных приложений",
    createdAt: "",
    updatedAt: "",
  },
];
