import { StoreTypes } from "types";

export const mockCommands: Array<StoreTypes.ICommand> = [
  {
    id: 1,
    departmentId: 14,
    name: "Разработка СД",
    taskIds: [],
    userIds: [1, 2],
    managerUserId: 1,
    description: "Команда по разработка Сд элементов",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    departmentId: 14,
    name: "Разработка приложений по мониторингу датчиков",
    taskIds: [],
    userIds: [3, 4],
    managerUserId: 3,
    description: "Команда по разработка приложений по мониторингу датчиков",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    departmentId: 14,
    name: "Разработка модулей фильтрации",
    taskIds: [],
    userIds: [5, 6],
    managerUserId: 5,
    description: "Команда по разработка модулей фильтрации",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    departmentId: 14,
    name: "Разработка корпоративных приложений",
    taskIds: [],
    userIds: [7, 8],
    managerUserId: 7,
    description: "Команда по разработка корпоративных приложений",
    createdAt: "",
    updatedAt: "",
  },
];
