import { StoreTypes } from "types";
import { mockCommands } from "./Commands";

export const mockUsers: Array<StoreTypes.IUser> = [
  {
    id: 1,
    login: "user-1",
    initials: "Кудрявцев Станислав Агафонович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 71,
    rating: 4,
    activeProjects: 1,
    commandName: mockCommands[0].name,
    phone: "79164100113",
    commandId: mockCommands[0].id,
    speed: 3,
    quality: 3,
    understanding: 4,
    sociability: 2,
    knowledge: 3,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    login: "user-2",
    initials: "Селезнёв Устин Арсеньевич",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 90,
    rating: 2,
    activeProjects: 1,
    commandName: mockCommands[0].name,
    phone: "79164100211",
    commandId: mockCommands[0].id,
    speed: 4,
    quality: 4,
    understanding: 4,
    sociability: 1,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    login: "user-3",
    initials: "Вишняков Петр Вениаминович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 100,
    rating: 1,
    activeProjects: 1,
    commandName: mockCommands[1].name,
    phone: "79164100211",
    commandId: mockCommands[1].id,
    speed: 5,
    quality: 4,
    understanding: 5,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    login: "user-4",
    initials: "Фомин Всеволод Германович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 85,
    rating: 3,
    activeProjects: 1,
    commandName: mockCommands[1].name,
    phone: "79164100211",
    commandId: mockCommands[1].id,
    speed: 4,
    quality: 4,
    understanding: 3,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 5,
    login: "user-5",
    initials: "Комиссаров Назарий Ефимович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 85,
    rating: 3,
    activeProjects: 1,
    commandName: mockCommands[2].name,
    phone: "79164100211",
    commandId: mockCommands[2].id,
    speed: 4,
    quality: 4,
    understanding: 3,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 6,
    login: "user-6",
    initials: "Трофимов Осип Викторович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 85,
    rating: 3,
    activeProjects: 1,
    commandName: mockCommands[2].name,
    phone: "79164100211",
    commandId: mockCommands[2].id,
    speed: 4,
    quality: 4,
    understanding: 3,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 7,
    login: "user-7",
    initials: "Васильев Гарри Рубенович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 85,
    rating: 3,
    activeProjects: 1,
    commandName: mockCommands[3].name,
    phone: "79164100211",
    commandId: mockCommands[3].id,
    speed: 4,
    quality: 4,
    understanding: 3,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 8,
    login: "user-8",
    initials: "Васильев Гарри Рубенович",
    password: "test",
    governance: "Управление разработки программных продуктов",
    department: "Отдел фронт-енд",
    jobTitle: "Программист",
    efficiency: 85,
    rating: 3,
    activeProjects: 1,
    commandName: mockCommands[3].name,
    phone: "79164100211",
    commandId: mockCommands[3].id,
    speed: 4,
    quality: 4,
    understanding: 3,
    sociability: 3,
    knowledge: 5,
    createdAt: "",
    updatedAt: "",
  },
];
